### ISSUE TITLE
I am unable to send email.

### ISSUE THREAD

**Issue by naumanafzal0313** [scheb/2fa#103]
I set the file like this

```
 email:
        enabled: true # If email authentication should be enabled, default false
        sender_email: me@example.com # Sender email address
        sender_name: John Doe # Sender name
        digits: 8 # Number of digits in authentication code
        template: security/2fa.html.twig
```

and installed swift mailer. but mail is not sending and but the email auth code is set in the database
