### ISSUE TITLE
Email code verification does not work when integrating with LexikJWTAuthenticationBundle

### ISSUE THREAD

**Issue by jpmmartin** [scheb/2fa#137]
**Bundle version**: 6.0.1
**Symfony version**: 5.4.5
**PHP version**: 8.1.4
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**
I am trying to integrate authentication with LexikJWTAuthenticationBundle with two-factor authentication but I do not receive the verification of the authentication code, I always get the answer that the code is not valid, I have followed all the steps explained here [https://symfony.com/bundles/SchebTwoFactorBundle/current/api.html](url) . I am not sure if the documentation is not clear enough now with what I should do or if I am doing something wrong.

**Additional Context**

**security.yml**
``` 
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: false
            jwt: ~
            json_login:
                check_path: /api/login_check
                success_handler: app.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            two_factor:
                prepare_on_login: true
                prepare_on_access_denied: true
                check_path: api_2fa_login_check
                authentication_required_handler: App\Security\TwoFactorAuthenticationRequiredHandler
                success_handler: App\Security\TwoFactorAuthenticationSuccessHandler
                failure_handler: App\Security\TwoFactorAuthenticationFailureHandler


    access_control:
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

**route.yml**
```
api_login_check:
    path: /api/login_check

api_2fa_login_check:
    path: /api/2fa_check

```

**service.yml**
```
parameters:

services:
    _defaults:
        autowire: true     
        autoconfigure: true 

 
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    app.handler.authentication_success:
        class: App\Security\AuthenticationSuccessHandler
        decorates: lexik_jwt_authentication.handler.authentication_success
        arguments: [ '@.inner' ]

```

**scheb_2fa.yaml**
```
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        enabled: true
        digits: 6
       sender_email: no-reply@example.com
```

**AuthenticationSuccessHandler**
```
<?php

declare(strict_types=1);

namespace App\Security;

use Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorTokenInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface;
use function json_decode;
use function json_encode;

final class AuthenticationSuccessHandler implements AuthenticationSuccessHandlerInterface
{
    public function __construct(private AuthenticationSuccessHandlerInterface $decoratedAuthenticationSuccessHandler)
    {
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token): Response
    {
        $response = $this->decoratedAuthenticationSuccessHandler->onAuthenticationSuccess($request, $token);
        if ($token instanceof TwoFactorTokenInterface) {
            $content = json_decode($response->getContent(), true);
            $content['login'] = 'success';
            $content['2fa_complete'] = false;

            $response->setContent(json_encode($content));

            return $response;
        }

        return $response;
    }
}
```

**TwoFactorAuthenticationFailureHandler**
```
<?php

declare(strict_types=1);

namespace App\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Exception\AuthenticationException;
use Symfony\Component\Security\Http\Authentication\AuthenticationFailureHandlerInterface;

final class TwoFactorAuthenticationFailureHandler implements AuthenticationFailureHandlerInterface
{
    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return new Response('{"error": "2fa_failed", "2fa_complete": false}');
    }
}
```

**TwoFactorAuthenticationRequiredHandler**
```
<?php

declare(strict_types=1);

namespace App\Security;

use Scheb\TwoFactorBundle\Security\Http\Authentication\AuthenticationRequiredHandlerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;


final class TwoFactorAuthenticationRequiredHandler implements AuthenticationRequiredHandlerInterface
{
    public function onAuthenticationRequired(Request $request, TokenInterface $token): Response
    {
        return new Response('{"error": "access_denied", "2fa_complete": false}');
    }
}
```

**TwoFactorAuthenticationSuccessHandler**
```
<?php

declare(strict_types=1);

namespace App\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface;

final class TwoFactorAuthenticationSuccessHandler implements AuthenticationSuccessHandlerInterface
{
    public function onAuthenticationSuccess(Request $request, TokenInterface $token): Response
    {
        return new Response('{"login": "success", "2fa_complete": true}');
    }
}
```

***Entity User.php***
```
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private ?string $email;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    #[ORM\Column(type: 'string')]
    private ?string $password;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $authCode;

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getAuthCode(): ?string
    {
        return $this->authCode;
    }

    public function setAuthCode(?string $authCode): self
    {
        $this->authCode = $authCode;

        return $this;
    }

    public function isEmailAuthEnabled(): bool
    {
        return true; // This can be a persisted field to switch email code authentication on/off
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        if (null === $this->authCode) {
            throw new \LogicException('The email authentication code was not set');
        }

        return $this->authCode;
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->authCode = $authCode;
    }
}

```

**Comment by scheb** [comment]
Please check your user entity in the database, if the authentication code is changing.

**Comment by jpmmartin** [comment]
> 

Yes the code in my database user entity is changing.

**Comment by scheb** [comment]
Then you should check your email delivery. Because then nothing is wrong with the bundle. The email is sent out, but it doesn't reach your mailbox.

**Comment by jpmmartin** [comment]
> Then you should check your email delivery. Because then nothing is wrong with the bundle. The email is sent out, but it doesn't reach your mailbox.

The email is being sent fine and with the same code that is in the database, I am verifying it in the email preview that the symfony profiler shows, but the problem I am having is not with the email, the problem is that the database and the email show me, for example, that the code is 834124 and then when I do the POST to /api/2fa_check with the body
```
{"data": {"authCode": "834124"}}
```
I always receive as a response
```
{"error": "2fa_failed", "2fa_complete": false}
```

And if I log in again and with username and password and change the code and try with the new code, it tells me that the code is invalid too.

**Comment by scheb** [comment]
Ah, sorry, I misread somehow and was under the impression the email not being sent is the problem. My bad.

Did you check what the `AuthenticationException $exception` says that you get passed in the `onAuthenticationFailure` method?

**Comment by jpmmartin** [comment]
> Ah, sorry, I misread somehow and was under the impression the email not being sent is the problem. My bad.
> 
> Did you check what the `AuthenticationException $exception` says that you get passed in the `onAuthenticationFailure` method?

The response I get from the expression is that the code is invalid. The response I get from the expression is that the code is invalid. At line 40 of Scheb\TwoFactorBundle\Security\Http\EventListener\CheckTwoFactorCodeListener.

I debug the CheckTwoFactorCodeListener with a dump to see the user and the code that is being passed to the CheckTwoFactorCodeListener->isValidCode and I get that the code that is being passed is an empty string.
This is the image of what I am sending using the postan:
![image](https://user-images.githubusercontent.com/24794238/162288244-08267d6d-c729-4acd-8934-20d55d347310.png)

**Comment by scheb** [comment]
You have to tell the bundle which field you're posting the auth code in. If you add this, it should work:

```yaml
security:
    firewalls:
        api:
            two_factor:
                auth_code_parameter_name: data.authCode
```
