### ISSUE TITLE
How to enable email + password for authentication

### ISSUE THREAD

**Issue by daan3011** [scheb/2fa#147]
Bundle version: 6.0
Symfony version: 6.0
PHP version: 8.1.5

Sorry in advance if this is a dumb question or I missed something obvious. I'm new to Symfony and I'm trying to implement 2fa with google authenticator on an api that uses Lexik JWT for authentication. We make use of a custom user provider that uses email + password combination for login and I think that that's the problem because the package doesn't check for that security token. Is there a configuration setting for changing the default user identifier or how could I implement this? Any help would be appreciated.

This is my firewall for reference:

``` yaml
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Clients
                property: email
    firewalls:
        login:
            pattern: ^/api/v1/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: email
                check_path: app_login
                success_handler: twoFa.authentication_success_two_fa_prompt
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                provider: app_user_provider
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                prepare_on_login: true
                prepare_on_access_denied: true
                authentication_required_handler: twoFa.accessDenied
                success_handler: twoFa.authentication_success
                failure_handler: twoFa.authentication_failure
        api:
            pattern:   ^/api
            stateless: false
            jwt: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa_login_check, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        # This ensures that the form can only be accessed when two-factor authentication is in progress.
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
```
