### ISSUE TITLE
Trusted device is ignored

### ISSUE THREAD

**Issue by dhodo** [scheb/2fa#16]
**Bundle version**: 5.0
**Symfony version**: 5.0.10

**Description**
Hi,

I was successful at implement the bundle and everything works as a charm. However, I am trying to implement the trusted_device functionality and it seems it is ignoring it. I debugged the program when log in and it enters in the function **getTrustedTokenVersion** I implemented in my provider but only to check if there is a trusted_device. It looks like the program neither write the field **trustedVersion** on the database nor generates any cookie.

This is my firewall in security.yaml:

   ```
 admin:
            pattern:    ^/[A-Za-z]{2}/admin
            anonymous: ~
            provider:    admin
            two_factor:
                auth_form_path: admin_2fa_login
                check_path: admin_2fa_login_check
            form_login:
                use_referer: true
                default_target_path: admin_home
                login_path:    admin_login
                check_path:    admin_login_check
            logout:
                path: admin_logout
                target: admin_login
                invalidate_session: false
```

This is my provider in security.yaml:
```
admin:
            entity:
                class: App\Entity\Admin
                property: user
```

This is my scheb_two_factor.yaml:
```
scheb_two_factor:

  trusted_device:
    enabled: true                 # If the trusted device feature should be enabled
    lifetime: 5184000              # Lifetime of the trusted device token
    cookie_name: wlAdmin_trust    # Name of the trusted device cookie
    cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
    cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax", "strict" or null
    cookie_domain: ".mydomain.com"  # Domain to use when setting the cookie, fallback to the request domain if not set
    cookie_path: "/"

  google:
    enabled: true                  # If Google Authenticator should be enabled, default false
    server_name: "Name of the server"       # Server name used in QR code
    issuer: "Name of the issuer"            # Issuer name used in QR code
    digits: 6                      # Number of digits in authentication code
    window: 1                      # How many codes before/after the current one would be accepted as valid
    template: A_General/Default/2fa_form.html.twig   # Template used to render the authentication form

```
