### ISSUE TITLE
How to use / configure a custom 2fa provider ?

### ISSUE THREAD

**Issue by PauchardThomas** [scheb/2fa#164]
**Bundle version**: 6.3.0
**Symfony version**: 6.0.11
**PHP version**: 8.1.10
**Using authenticators** (`enable_authenticator_manager: true`): YES / NO

**Description**

Hello, i'm trying to implement a custom two-factor provider.
Following the [doc](https://symfony.com/bundles/SchebTwoFactorBundle/6.x/providers/custom.html#register-the-provider), i registered my service as described : 

```yaml
    app.twilio_two_factor_provider:
        class: App\Infrastructure\TwoFa\TwilioTextSenderProvider
        public: true
        tags:
            - { name: scheb_two_factor.provider, alias: twilio_two_factor_provider }
```

Then add it to the  `scheb_two_factor.yaml` file : 

```yaml
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    twilio_two_factor_provider:
        enabled: true
```

But got an Exception :

_Unrecognized option "twilio_two_factor_provider" under "scheb_two_factor". Available options are "email", "google", "ip_whitelist", "ip_whitelist_provider", "model_manager_name", "persister", "security_tokens", "trusted_device", "two_factor_condition", "two_factor_token_factory"._

What am I doing wrong ?

Thanks

Ps : Got the same problem when trying to use  https://github.com/Erkens/2fa-text
