### ISSUE TITLE
AWS AutoScalingGroup server change invalidates secret

### ISSUE THREAD

**Issue by Kamuza** [scheb/2fa#17]
**Bundle version**: 5.0
**Symfony version**: 5.0.10

**Description**
Hi, when I change server capacity in AWS (that is, when I change the server), the authenticator code becomes invalid, and I have to resync with a new secret, which is not valid for a production environment.

Is there a way to be able to change servers and keep the secret code valid? This is my firewall from security.yaml:

```
admin:
    pattern:    ^/admin
    anonymous: ~
    provider:    admin
    two_factor:
        auth_form_path: admin_2fa_login
        check_path: admin_2fa_login_check
        trusted_parameter_name: admin_trusted
```

Thank you.

**Comment by scheb** [comment]
The secret code should be stored in the database together with the user entity. So that code shouldn't change when you switch machines, therefore the Google Authenticator codes should just keep working.

I suspect the UTC time on the AWS machine and your mobile device might be slightly (some seconds) off. For your mobile device, there should by a "Settings > Time Correction for Codes > Sync now" option, to synchronize the time on your phone. For the AWS server you could print out a Unix timestamp and check how much it's different from actual UTC time. I'd actually expect that AWS servers automatically sync time, so it's probably your mobile device's time, which is off.

To compensate for the time difference between server and mobile device you could also increase the `window` in the configuration.
```yaml
# config/packages/scheb_two_factor.yaml
scheb_two_factor:
    google:
        window: 1                      # How many codes before/after the current one would be accepted as valid
```

**Comment by Kamuza** [comment]
I already store the secret code in a AWS RDS database, and I don't notice any time desynchronization. 
Still, I have used chronyd to sync both servers and try to enter the code. When I use chronyd on the server where I establish double authentication for the first time, I can access with the code without problem, but when I change the server and use chronyd again, ensuring that the time is synchronized, I get a 'The verification code is not valid' message.

This is my yaml:

```yaml
# config/packages/scheb_two_factor.yaml
google:
    enabled: true                  
    server_name: "server name" 
    issuer: "issuer"
    digits: 6
    window: 1
    template: A_General/Default/2fa_form.html.twig
```

Thanks for you help!
