### ISSUE TITLE
Unable to find the controller for path "/2fa_check". The route is wrongly configured.

### ISSUE THREAD

**Issue by FBL-dev** [scheb/2fa#170]
**Bundle version**: 6.4.0
**Symfony version**: 6.2.2
**PHP version**: 8.1.13
**Using authenticators** (`enable_authenticator_manager: true`):

**Description**

I am trying to create a custom two-factor provider with duo (https://github.com/duosecurity/duo_universal_php).
However, here is the error I get and I can't find a solution:

`Unable to find the controller for path "/2fa_check". The route is wrongly configured.`

I created a new form renderer class because I need to send the user to an external link (to duo) and I think the problem comes from there but I can't find a solution.

```
public function renderForm(Request $request, array $templateVars): Response
{
    $email = $this->requestStack->getSession()->get('email');

    $duo_client = new Client(
        client_id: 'xx',
        client_secret: 'xx',
        api_host: 'xx',
        redirect_uri: 'http://localhost:3000/2fa_check'
    );

    $state = $duo_client->generateState();
    $prompt_uri = $duo_client->createAuthUrl($email, $state);

    return new RedirectResponse($prompt_uri);
}
```

When the authentication is validated on the duo site, I am redirected to "http://localhost:3000/2fa_check" and this is where I get the error indicated above.

Can you tell me if there is a solution to my problem?
Thank you

**Additional Context**

```
//security.yaml
firewalls:
    main:
        pattern: ^/
        lazy: true
        login_throttling: ~ #5 attemps by minute
        remember_me:
            secret:   '%kernel.secret%'
            lifetime: 604800 # 1 week in seconds
            path:     /
        switch_user: true
        custom_authenticators:
           - App\Security\LoginFormAuthenticator
        form_login:
            enable_csrf: true
        user_checker: App\Security\UserChecker
        two_factor:
            auth_form_path: 2fa_login
            check_path: 2fa_login_check
        logout:
            path: security_logout
            target: home_index
            enable_csrf: true
        entry_point: App\Security\LoginFormAuthenticator
```

```
//routes/scheb_2fa.yaml
2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa_check
```

```
//services.yaml
acme.custom_two_factor_provider:
    class: App\Security\DuoAuthenticatorTwoFactorProvider
    autowire: true
    tags:
        - { name: scheb_two_factor.provider, alias: duo_two_factor_provider }

app.custom_form_renderer:
    class: App\Security\DuoFormRenderer
    arguments:
        - '@twig'
```

**Comment by scheb** [comment]
Since that duo authentication is obviously redirecting to the 2fa check route, you likely need to activate GET requests on that route:

```yaml


# config/packages/security.yaml
security:
    firewalls:
        your_firewall_name:
            # ...
            two_factor:
                post_only: false
```
