### ISSUE TITLE
Redirects back to form login

### ISSUE THREAD

**Issue by graferowy** [scheb/2fa#184]
**Bundle version**: 6.8.0
**Symfony version**: 5.4.15
**PHP version**: 8.1
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

Is a TwoFactorToken present after the login?
No, it redirects me to the 2fa_login and then immediately back to the login form.

On login, do you reach the end (return statement) of method Scheb\TwoFactorBundle\Security\Authentication\Provider\AuthenticationProviderDecorator::authenticate()?
No idea, there's no such class or method in given namespace

On login, is method Scheb\TwoFactorBundle\Security\TwoFactor\Handler\TwoFactorProviderInitiator::getActiveTwoFactorProviders() called?
Yes, it returns array with my custom provider.

**To Reproduce**

1. Login form at /admin/login redirects me to /
2. / redirects me to 2fa_login ( /admin/2fa )
3. 2fa_login ( /admin/2fa ) redirects me back to /admin/login

/ is publicly accessible. If I set default_target_path on my login form to restricted area it looks like this

1. Login form at /admin/login redirects me to /admin/dashboard
2. /admin/dashboard immediately redirects me back to /admin/login

Only beginAuthentication of my custom provider is being called. App does not reach prepareAuthentication.

**Additional Context**

security.yaml
```
security:
    enable_authenticator_manager: true
    ...

    providers:
        ...
    firewalls:
        ...
        admin:
            form_login:
                login_path: admin_login
                check_path: admin_login
            logout:
                path: admin_logout
                target: admin_login
            remember_me:
                lifetime: 2629800
                path: '/admin'
                secret: '%kernel.secret%'
            provider: admins
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: admin_dashboard
        main:
            lazy: true
            provider: users_in_memory

    access_control:
         - { path: ^/admin/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
         - { path: ^/api/doc, roles: PUBLIC_ACCESS }
         - { path: ^/admin/login, roles: PUBLIC_ACCESS }
         - { path: ^/admin, roles: ROLE_ADMIN }
```

services.yaml
```
services:
    App\Security\TwoFactor\Provider\SmsTwoFactorProvider:
        tags:
            - { name: scheb_two_factor.provider, alias: sms_two_factor_provider }
```

Custom Provider
```
class SmsTwoFactorProvider implements TwoFactorProviderInterface
{
    public function __construct(
        private readonly TwoFactorFormRendererInterface $formRenderer,
        private readonly CodeGenerator $codeGenerator
    ) {
    }

    public function beginAuthentication(AuthenticationContextInterface $context): bool
    {
        $admin = $context->getUser();

        return $admin instanceof Admin;
    }

    public function prepareAuthentication(object $user): void
    {
        if (!$user instanceof TwoFactorInterface) {
            return;
        }

        $this->codeGenerator->generateAndSend($user);
    }

    public function validateAuthenticationCode(object $user, string $authenticationCode): bool
    {
        if (!$user instanceof TwoFactorInterface) {
            return false;
        }

        $authenticationCode = str_replace(' ', '', $authenticationCode);

        return $user->getTwoFactorAuthCode() === $authenticationCode;
    }

    public function getFormRenderer(): TwoFactorFormRendererInterface
    {
        return $this->formRenderer;
    }
}
```
