### ISSUE TITLE
Bundle not work in PHP 8.2 but work in 8.1

### ISSUE THREAD

**Issue by ph1823** [scheb/2fa#189]
**Bundle version**: 6.8.0 (tested in 6.5 and 6.7)
**Symfony version**: 6.2.7
**PHP version**: 8.2.6
**Using authenticators** (`enable_authenticator_manager: true`): NO

**Description**

When i have update to PHP 8.2 in my server, i have no problem.
But now i have update to le latest version of 2f-bundle and my login doest work.
I have don't touch to the code, juste update my PHP version.

**To Reproduce**

1. Make basic auth with 2fa
2. Take PHP 8.1
3. Test if you auth work
4. Upgrade to PHP 8.2
5. Test if you auth work 

**Additional Context**
bundle config:
```yaml
# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Acme\AuthenticationBundle\Token\CustomAuthenticationToken
    google:
        enabled: true
        issuer: DataHosting            # Issuer name used in QR code
        template: "datahosting/site/security/2fa.html.twig"
    # Email authentication config
    email:
        enabled: true                  # If email authentication should be enabled, default false
        sender_email: noreply@datahosting.fr   # Sender email address
        sender_name: DataHosting         # Sender name
        digits: 4                      # Number of digits in authentication code
        template: "datahosting/site/security/2fa.html.twig"   # Template used to render the authentication form
```

security config:
```yaml
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
      # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
          two_factor:
            auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
            check_path: 2fa_login_check  # The route name you have used in the routes.yaml
            success_handler: App\Security\TwoFactorAuthenticationSuccessHandler
            prepare_on_login: true
            prepare_on_access_denied: true
          form_login:
            use_referer: true
            login_path: app_login
          lazy: true
          custom_authenticators:
              - App\Security\AppAuthenticator
              - App\Security\FacebookAuthenticator
              - App\Security\DiscordAuthenticator
              - App\Security\GoogleAuthenticator
              - App\Security\TwitterAuthenticator
              - App\Security\ApiKeyAuthenticator
          entry_point: App\Security\AppAuthenticator
          logout:
            path: app_logout
            target: home
          remember_me:
            secret: '%kernel.secret%'
            lifetime: 31540000 # 1 years in seconds
            path: /
            secure: true
            # by default, the feature is enabled by checking a
            # checkbox in the login form (see below), uncomment the
            # following line to always enable it.
            #always_remember_me: true
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    #IS_AUTHENTICATED_REMEMBERED
    access_control:
      - { path: ^/discord, role: ROLE_BETA }
      - { path: ^/admin, roles: ROLE_STAFF }
      - { path: ^/admin/*, roles: ROLE_STAFF }
      - { path: ^/beta, role: ROLE_BETA }
      - { path: ^/gmod, role: ROLE_BETA }
      - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED, host: ^manager\.datahosting\.fr$ }
      - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED, host: ^support\.datahosting\.fr$}
      - { path: ^/datacoins/gagner, roles: PUBLIC_ACCESS }
      - { path: ^/datacoins, roles: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/calendrier-avant, roles: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/renew, roles: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/cart, roles: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/membre, roles: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/efconnect, role: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/elfinder, role: IS_AUTHENTICATED_REMEMBERED }
      - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
      - { path: ^/, roles: PUBLIC_ACCESS }
```
No idea where is problem. I have check in 6.5, 6.7 and 6.8 and same problem with PHP 8.2 but no problem with PHP 8.1.

Thank for reading me !
