### ISSUE TITLE
Will 2fa work with sessions disabled?

### ISSUE THREAD

**Issue by jwage** [scheb/2fa#190]
**Bundle version**: v6.6.0
**Symfony version**: 5.4.11
**PHP version**: 8.1.18
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

I am disabling built in sessions and csrf protection in my application, so I am changing this configuration:

```
    session:
        storage_factory_id: session.storage.factory.native
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_secure: auto
        cookie_samesite: lax
        cookie_domain: '%env(COOKIE_DOMAIN)%'
        name: 'TPSESSIONID'
```

and replacing with this:

```
    session: false
```

I am using this with a standard `remember_me` and `form_login`:

```
            remember_me:
                secret:             '%kernel.secret%'
                lifetime:           31536000
                path:               /
                always_remember_me: true
                domain:             '%env(COOKIE_DOMAIN)%'
                name:               'TPREMEMBERME'

            form_login:
                enable_csrf: false
                login_path: login
                check_path: login
                use_referer: true
                default_target_path: login_success
```

When I disable sessions, the 2fa form does not show after I submit the login form. Does scheb/2fa depend on the session currently?
