### ISSUE TITLE
[idea] Auto close PR on sub-repositories

### ISSUE THREAD

**Issue by Spomky** [scheb/2fa#2]
Some developers may think that PRs have to be submitted in sub-repositories.
To avoid that, ou should automatically close these PRs and warn the devlopers.

In general, I use [Stale](https://github.com/marketplace/stale), a free bot from the marketplace, with the following configuration:

```yaml
daysUntilStale: 1
daysUntilClose: 1
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because this repository
  is a read-only repository and nobody will take care of it.
  **Please submit it to the main repository.**
  Thank you for your contributions.
closeComment: false
```

That configuration has to be placed in the `.github/stale.yml` of each split folder (e.g. `src/backup-code/.github/stale.yml`)
