### ISSUE TITLE
Problem when switching to PROD

### ISSUE THREAD

**Issue by Erp-Link** [scheb/2fa#202]
**Bundle version**: ^6.9
**Symfony version**: 6.3.4
**PHP version**: 8.1.23
**Using authenticators** (`enable_authenticator_manager: true`): NO

**Description**
Hi

When I am in a DEV environment and I enter the code received by email for double authentication it works without problem.

However, when I switch the site to a PROD environment on (the same machine), I get an error 500 after entering the authentication code...

If I put APP_DEBUG=1 in the env.local file then even in a PROD environment it works.

I don't understand the problem, can you help me please?

Thank you in advance
Mickaël 

**Additional Context**

```
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
            switch_user: true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 2628000 #2628000 = 1 month in seconds, 604800 = 1 week in seconds
                signature_properties: ['password', 'updatedAt']
                path:     /
                #token_provider:
                #    doctrine: true
                always_remember_me: true   
            login_throttling:
                max_attempts: 2 

            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                enable_csrf: true
                post_only: true              # If the check_path should accept the code only as a POST request
                default_target_path: dashboard_home 
                always_use_default_target_path: true # If it should always redirect to default_target_path
                trusted_parameter_name: _trusted  # Name of the parameter for the trusted device option
                multi_factor: false                    # If ALL active two-factor methods need to be fulfilled (multi-factor authentication)
```

Config : 

```
# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        #- Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    
    # Google Authenticator config
    google:
        enabled: true                  # If Google Authenticator should be enabled, default false
        server_name: Server Name       # Server name used in QR code
        issuer: Issuer Name            # Issuer name used in QR code
        window: 1                      # How many codes before/after the current one would be accepted as valid
        template: Frontend/security/2fa_form.html.twig   # Template used to render the authentication form


    # Email authentication config
    email:  
        digits: 6
        enabled: true
        sender_email: security@*****@gmail.com
        sender_name: Mickael
        template: Frontend/security/2fa_form.html.twig


    
    trusted_device:
        enabled: true                  # If the trusted device feature should be enabled
        lifetime: 5184000              # Lifetime of the trusted device token
        extend_lifetime: false         # Automatically extend lifetime of the trusted cookie on re-login
        cookie_name: trusted_device    # Name of the trusted device cookie
        cookie_secure: false           # Set the 'Secure' (HTTPS Only) flag on the trusted device cookie
        cookie_same_site: "lax"        # The same-site option of the cookie, can be "lax" or "strict"
        cookie_domain: ".127.0.0.1"    # Domain to use when setting the cookie, fallback to the request domain if not set
        cookie_path: "/"               # Path to use when setting the cookie

    
      
    # A list of IP addresses, which will not trigger two-factor authentication
    ip_whitelist:
       - 127.0.0.2 # Used for testing
```
