### ISSUE TITLE
How to have Google authenticator required to be setup even after first login ?

### ISSUE THREAD

**Issue by allan-simon** [scheb/2fa#203]
I've checked 
https://symfony.com/bundles/SchebTwoFactorBundle/current/troubleshooting.html

**Bundle version**:  6.9.0
**Symfony version**: 6.3.5
**PHP version**: 8.1.20
**Using authenticators** (`enable_authenticator_manager: true`): YES (mandatory in 6.2+)

**Description**

I want Google Authenticator to be mandatory on my application.

Hence I thought about doing the following flow:

1. you login for the first time (the email / password is already set by an admin, so you don't need to register first, you directly login)
2.  if you try to access any "authenticated user only" page and you have not it setup yet, you a redirected to the page asking you to configure it.

I block at the step 2. 

While I could do a hackish  check in the  `/dashboard`  method to  check if there's a google secret, and if not redirecting it would only be a security theater as other pages will not have the check (I could do it for every single page but ....)

I've tried to do

```
public function isGoogleAuthenticatorEnabled(): bool
{
   return true;
}
```

but it fails with `User has to provide a secret code for Google Authenticator authentication.` 

Which I think is normal because this condition is supposed to be used to enter a code for an existing authenticator

As I'm not familiar enough with Symfony's internal I'm not sure if the best solution is

1. to create my owner GoogleRequiredAuthenticator that either display a "setup" form  or a "enter code" form ?
2. Have my own listener (which kind of listener on which event ?) to intercept  the event before and redirect ?
3. something else ?

 

**Additional Context**

my package config:
```
scheb_two_factor:
    google:
        enabled: true
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Symfony\Component\Security\Core\Authentication\Token\RememberMeToken

```

```
        company_admins:
            host: companies.*
            pattern: ^/
            two_factor:
               auth_form_path: company_admin_2fa_login
               check_path: company_admin_2fa_login_check
            form_login:
                login_path: company_admins_login
                check_path: company_admins_login
                default_target_path: company_admins_dashboard
                enable_csrf: true
                use_referer: true
            entry_point: form_login
    access_control:
        # allow unauthenticated users to access the login form
        - { host: companies.*, path: ^/login, roles: PUBLIC_ACCESS }
        # This ensures that the form can only be accessed when two-factor authentication is in progress.
        - { host: companies.*, path: ^/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { host: companies.*, path: ^/, roles: ROLE_COMPANY_ADMIN}
```
