### ISSUE TITLE
2fa_login  and 2fa_login_check  can't be replaced by our own route name

### ISSUE THREAD

**Issue by allan-simon** [scheb/2fa#204]
**Bundle version**:  6.9.0
**Symfony version**: 6.3.5
**PHP version**: 8.1.20
**Using authenticators** (`enable_authenticator_manager: true`): YES (mandatory in 6.2+)

**Description**

As in my project I have a routing based on subdomain and I will want in the future to have different 2fa configuration I was thinking to have dedicated  login / check route for 2fa by doing 
```
# config/routes/scheb_2fa.yaml
my_own_2fa_login:
    path: /2fa
    host: '{subdomain}'
    requirements:
        subdomain: 'companies.*'
    defaults:
        # "scheb_two_factor.form_controller" references the controller service provided by the bundle.
        # You don't HAVE to use it, but - except you have very special requirements - it is recommended.
        _controller: "scheb_two_factor.form_controller::form"
        subdomain: '%companies_domain%'
    
my_own_2fa_login_check:
    host: '{subdomain}'
    requirements:
        subdomain: 'companies.*'
    path: /2fa_check
    defaults:
        subdomain: '%companies_domain%'
```

and in my `security.yaml` 

```
            two_factor:
               auth_form_path: my_own_2fa_login  
               check_path:  my_own_2fa_check
```

but then, even though the form was displaying correctly, when I was submitting it

I had the error: 

```
Unable to find the controller for path "/2fa_check". The route is wrongly configured.
```

and in the debug I was seeing a route `2fa_check` being matched , as it was added automatically by the bundle and overriding  my  route

reverting back the route name to their original ones  fixed the problem

**Additional Context**

Is it expected ? Which I may understand but in that case the documentation may stress out more that it **must** be these values
