### ISSUE TITLE
Validate code before actual Google Authentication / Different BruteForce protection compared to documentation

### ISSUE THREAD

**Issue by hracik** [scheb/2fa#208]
**Description**

At the moment when user submits empty field or the length isn't the same as expected - default is 6, or typed letters it is validated by against the actual code which seems slower than validating with NotBlank or Lenght and only after that validate the actual code.

Bundle says in [documentation ](https://symfony.com/bundles/SchebTwoFactorBundle/6.x/brute_force_protection.html) that brute force is not enabled by default and some listeners are needed, but I did not write any and after I submitted a couple of empty code I got error Too many failed login attempts, please try again in 12 minutes and a bit later Too many failed login attempts, please try again in 50 minutes from symfony/security.

Seem like login_throttling in the firewall is doing the job.
```
login_throttling:
max_attempts: 3
interval: '60 minute'
```

My firewall 
```
firewalls:
        main:
            login_throttling:
                max_attempts: 3
                interval: '60 minute'
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout
            switch_user: true
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
            user_checker: App\Security\UserChecker
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
                enable_csrf: true
```
