### ISSUE TITLE
symfony 5.4 firewall with custom_authenticator 

### ISSUE THREAD

**Issue by nathanphan** [scheb/2fa#210]
**Bundle version**: 6.9
**Symfony version**: 5.4
**PHP version**: x.y.z
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

This is my security.yaml

```yaml
security:
  enable_authenticator_manager: true  
firewalls:
    dev:
      pattern: '^/(_(profiler|wdt)|css|images|js)/'
      security: false
    main:
      lazy: false
      custom_authenticators:
        - MyApp\Security\TokenAuthenticator
      two_factor:
        auth_form_path: api_login
        check_path: api_2fa_check
        trusted_parameter_name: _trusted 
        prepare_on_login: true
        prepare_on_access_denied: true
        authentication_required_handler: MyApp\SecurityTwoFactorAuthenticationRequiredHandler
        success_handler: MyApp\Security\TwoFactorAuthenticationSuccessHandler
        failure_handler: MyApp\Security\TwoFactorAuthenticationFailureHandler
        auth_code_parameter_name: data.authCode 
   
      json_login:
        success_handler: MyApp\Security\TwoFactorAuthenticationSuccessHandler
      logout:
        path: /logout # to add logoutListener for 2FA
        invalidate_session: true
```

I have a LoginHanlder which will response token in JSON format when API /login is called. The token is returned perfectly.

Then I use that returned token to call another API let's say /get-info. this time it returns 
`{
    "error": "2fa_required",
    "two_factor_complete": false
}`

Then I use the auth_code generated in database Users table to access /2fa_check
with Request:
`{
    "data": {
        "authCode": "946997"
    }
}`

and get the response
`{
    "status": "error",
    "error": {
        "key": "An authentication exception occurred.",
        "message": "The two-factor provider \"email\" has not been prepared."
    }
}`

What I obsered is that
TwoFactorProviderPreparationListener::onLogin is called. and the log is generated like this
`"message":"Two-factor provider \"email\" prepared."`

Please suggest me how it should work? I mean the flow when the custom authenticator is called to authenticate the token. What event is expected in this case to let
