### ISSUE TITLE
Infinite redirection loop problem

### ISSUE THREAD

**Issue by secit-pl** [scheb/2fa#213]
**Bundle version**: 7.0.0
**Symfony version**: 7.0.1
**PHP version**: 8.2.10

**Description**

Throwing an exception in `user_checker` `checkPostAuth()` ends in infinite redirection loop.

**To Reproduce**

0. Configure bundle using email tokens.
1. Add user checker in `security.yaml`
```yaml
security:
  firewalls:
    website:
      lazy: true
      provider: app_user_provider
      user_checker: App\Security\UserChecker
      ...
```
2. `App\Security\UserChecker`
```php
<?php

namespace App\Security;

use Symfony\Component\Security\Core\Exception\CredentialsExpiredException;
use Symfony\Component\Security\Core\User\UserCheckerInterface;
use Symfony\Component\Security\Core\User\UserInterface;

class UserChecker implements UserCheckerInterface
{
    public function checkPreAuth(UserInterface $user): void
    {
    }

    public function checkPostAuth(UserInterface $user): void
    {
        throw new CredentialsExpiredException();
    }
}
```

3. Now login as usual, enter the code from the mail, submit form and you will get the infinite redirection loop.

<img width="666" alt="image" src="https://github.com/scheb/2fa/assets/24696884/60d7c12f-5ce2-4226-8143-c3c8f30c608d">
