### ISSUE TITLE
Custom code generator and mailer

### ISSUE THREAD

**Issue by Quezako** [scheb/2fa#22]
**Bundle version**: 5.*
**Symfony version**: 4.4

**Description**
Hello,

I'm trying to follow this documentation, but the yaml config throws some errors. I'm don't know Symfony enough to understand what I am doing wrong.
https://github.com/scheb/2fa/blob/5.x/doc/providers/email.md

The full question here:
https://stackoverflow.com/questions/63515165/symfony-4-4-scheb-2fa-custom-code-generator-and-mailer
**Additional Context**

**Comment by scheb** [comment]
Your issue is not related to the bundle, but related to your service configuration. Symfony is using "auto-wiring" to connect instances of classes based on their class name, when they're not explicitly configured. Interfaces cannot be auto-wired, since you cannot create an instance of an interface and Symfony doesn't know which implementation of the interface should be instantiated.

So you have to configure a service and reference that service using the `@` annotation to tell Symfony to use that service instance. Have a look at the docs: https://symfony.com/doc/current/service_container.html#service-parameters

In my opinion the following configuration should work:
```yaml
services:
    # ...
    auth_mailer:
        class: App\Mailer\MyAuthCodeMailer

    code_generator_service:
        class: App\Service\CodeGeneratorService
        arguments:
            $mailer: "@auth_mailer"
            $digits: "%scheb_two_factor.email.digits%"
```
