### ISSUE TITLE
Conditional lifetime of the trust device cookie

### ISSUE THREAD

**Issue by sdespont** [scheb/2fa#250]
Hello,

I would like to use different lifetimes for trusted device cookies for the user or administrator.

In a custom trusted device manager, would it be possible to set different lifetimes based on custom conditions?

```
# config/packages/scheb_2fa.yaml
scheb_two_factor:
    trusted_device:
        manager: acme.custom_trusted_device_manager  # Use a custom trusted device manager
```
