### ISSUE TITLE
Configurable with environment variables

### ISSUE THREAD

**Issue by Adambean** [scheb/2fa#254]
Hello,

Would it be possible to support this component's configuration to be read from environment variables?

The purpose of this would be so that the configuration can be semi-exposed via service parameters to templating or API. This would allow a user account 2FA management interface to adapt according to the application's configuration without duplication of or detachment from the component's configuration. For example only showing a section for activating/managing Google Authenticator if it's been enabled in the component configuration.

This would also allow the configuration to be injected into translation messages, such as a span or tooltip alongside the "This is a trusted device" checkbox to inform the user how long their device will be remembered for.

I did attempt this though it encounters issues. (It may already work with me just getting it wrong instead.)

* When trying to set "scheb_two_factor.email.enabled" with `"%env(bool:2FA_EMAIL_ENABLED)%"`:
  > Using a cast in "env(bool:2FA_EMAIL_ENABLED)" is incompatible with resolution at compile time in "Scheb\TwoFactorBundle\DependencyInjection\SchebTwoFactorExtension". The logic in the extension should be moved to a compiler pass, or an env parameter with no cast should be used instead.
* When trying to set "scheb_two_factor.email.enabled" with `"%env(2FA_EMAIL_ENABLED)%"`, same as above without a boolean processor:
  The value is always loosely juggled to `false` from an empty string.
* When trying to set "scheb_two_factor.trusted_device.lifetime" `"%env(int:2FA_TRUSTED_DEVICE_LIFETIME)%"`:
  The value is always loosely juggled to a `0` from an empty string.
  > The value 0 is too small for path "scheb_two_factor.trusted_device.lifetime". Should be greater than or equal to 1
* When trying to set "scheb_two_factor.trusted_device.lifetime" `"%env(2FA_TRUSTED_DEVICE_LIFETIME)%"`, same as above without an int processor:
  The value is always seen as an empty string.
  > Invalid type for path "scheb_two_factor.trusted_device.lifetime". Expected "int", but got "string".

Example environment variables:

```env
2FA_EMAIL_ENABLED=true
2FA_EMAIL_DIGITS=6
2FA_GOOGLE_AUTHENTICATOR_ENABLED=true
2FA_GOOGLE_AUTHENTICATOR_LEEWAY=3
2FA_TRUSTED_DEVICE_ENABLED=true
2FA_TRUSTED_DEVICE_LIFETIME=604800
2FA_BACKUP_CODES_ENABLED=true
```

Example "scheb_2fa.yaml" configuration:

```yaml
parameters:
    2fa_email_enabled: "%env(bool:2FA_EMAIL_ENABLED)%"
    2fa_email_digits: "%env(int:2FA_EMAIL_DIGITS)%"
    2fa_google_authenticator_enabled: "%env(bool:2FA_GOOGLE_AUTHENTICATOR_ENABLED)%"
    2fa_google_authenticator_leeway: "%env(int:2FA_GOOGLE_AUTHENTICATOR_LEEWAY)%"
    2fa_trusted_device_enabled: "%env(bool:2FA_TRUSTED_DEVICE_ENABLED)%"
    2fa_trusted_device_lifetime: "%env(int:2FA_TRUSTED_DEVICE_LIFETIME)%"
    2fa_backup_codes_enabled: "%env(bool:2FA_BACKUP_CODES_ENABLED)%"

scheb_two_factor:
    email:
        enabled: "%2fa_email_enabled%"
        digits: "%2fa_email_digits%"

    google:
        enabled: "%2fa_google_authenticator_enabled%"
        leeway: "%2fa_google_authenticator_leeway%"

    trusted_device:
        enabled: "%2fa_trusted_device_enabled%"
        lifetime: "%2fa_trusted_device_lifetime%"

    backup_codes:
        enabled: "%2fa_backup_codes_enabled%"

twig:
    globals:
        2fa_email_enabled: "%2fa_email_enabled%"
        2fa_email_digits: "%2fa_email_digits%"
        2fa_google_authenticator_enabled: "%2fa_google_authenticator_enabled%"
        2fa_google_authenticator_leeway: "%2fa_google_authenticator_leeway%"
        2fa_trusted_device_enabled: "%2fa_trusted_device_enabled%"
        2fa_trusted_device_lifetime: "%2fa_trusted_device_lifetime%"
        2fa_backup_codes_enabled: "%2fa_backup_codes_enabled%"
```
