### ISSUE TITLE
Configurable email digits with environment variables

### ISSUE THREAD

**Issue by tomas-kulhanek** [scheb/2fa#261]
**Bundle version**: 7.6.0
**Symfony version**: 7.2 and 7.3 beta
**PHP version**: 8.4.2

**Description**

Hi, could I ask for some advice on the configuration? I'm trying to set `scheb_two_factor.email.digits` with the value from the env variable, but I keep getting the error below. Other variables work fine.

![Image](https://github.com/user-attachments/assets/090aecd9-82fb-41a0-8439-e228d04be4a3)

**Additional Context**
My `.env` file
```env
TWO_FA_EMAIL_DIGITS=65
```
`config/packages/scheb_2fa.yaml`
```yaml
scheb_two_factor:
    totp:
        enabled: true
        server_name: '%env(string:TWO_FA_SERVER_NAME)%'
        issuer: '%env(string:TWO_FA_ISSUER)%'
        leeway: '%env(int:TWO_FA_TOTP_LEEWAY)%'
        parameters: 
            image: '%env(string:TWO_FA_IMAGE)%'
    email: 
        enabled: true
        digits: '%env(int:TWO_FA_EMAIL_DIGITS)%'
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
```

And I also tried php
`config/packages/scheb_2fa.php`
```php
<?php

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken;
use Symfony\Config\SchebTwoFactorConfig;

use function Symfony\Component\DependencyInjection\Loader\Configurator\env;

return static function (
    ContainerConfigurator $containerConfigurator,
    SchebTwoFactorConfig $encryptionConfig
): void {
    $encryptionConfig->totp([])
        ->enabled(true)
        ->serverName(env('TWO_FA_SERVER_NAME')->string())
        ->issuer(env('TWO_FA_ISSUER')->string())
        ->leeway(env('TWO_FA_TOTP_LEEWAY')->int())
        ->parameters([
            'image' => env('TWO_FA_IMAGE')->string()
        ]);

    $encryptionConfig->email([])
        ->enabled(true)
        ->digits(env('TWO_FA_EMAIL_DIGITS')->int());
    $encryptionConfig->securityTokens([
        UsernamePasswordToken::class,
        PostAuthenticationToken::class
    ]);
};
```
