### ISSUE TITLE
Authenticator does not support the request for 7.6.0

### ISSUE THREAD

**Issue by danardf** [scheb/2fa#262]
**Bundle version**: v7.6.0
**Symfony version**: 7.2.2
**PHP version**: 8.3

**Description**

Hi Everyone.

As usual, I'm trying to update my project often (composer update, npm update...etc). 
One day, my session has expired and I logged in again and the auth_code has been sent by email.
When I try to enter the code, The page is reloded. 

With the cmd line : **symfony server:log**
It returns this:

```
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Checking for authenticator support. authenticators=3 firewall_name="main"
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Checking support on authenticator. authenticator="Symfony\\Component\\Security\\Http\\Authenticator\\Debug\\TraceableAuthenticator"
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Authenticator does not support the request.
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Checking support on authenticator.
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Authenticator does not support the request.
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Checking support on authenticator.
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Authenticator does not support the request.
[Application] Jan 24 18:59:10 |DEBUG  | SECURI Stored the security token in the session. key="

```

I have the same project on prod (not updated) and the 2fa works as expected. 
No problem.

```
        main:
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: homepage
```

```
2fa_login:
    path: /2fa
    defaults:
        _controller: "scheb_two_factor.form_controller::form"

2fa_login_check:
    path: /2fa_check
```

I'm fighting to find where the issue comes from. No way.

I wonder if there is a bug or maybe a new type of settings. 

Thanks 

Franck
