### ISSUE TITLE
Upgraded to Symfony 6.4 from 5 ad 2FA never triggers

### ISSUE THREAD

**Issue by pixiekat** [scheb/2fa#272]
**Bundle version**: 7.5.0
**Symfony version**: 6.4.10
**PHP version**: 8.3.19

**Description**

I recently upgraded from an older install of Symfony (5.x to 6.4) as I was upgrading the server and application. I'm currently using chrishemmings/oauth2-drupal and a custom authenticator, which I was using before I upgraded and 2FA worked fine. 

However since the upgrade, I log in fine normally through the oauth process and I receive a PostAuthenticationToken but the 2FA never triggers. It just immediately logs me in (and /2fa gives access denied since I'm logged in).

This is my scheb_2fa.yml:

```yaml
scheb_two_factor:
    email:
        digits: 6
        enabled: true
        mailer: app.auth_code_mailer_service
        sender_email: <sender email>
        sender_name: <title of app>
        template: security/2fa_form.html.twig
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        # If you're using guard-based authentication, you have to use this one:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
    trusted_device:
        enabled: true 
        lifetime: 31536000
        extend_lifetime: true  
        cookie_name: trusted_device
        cookie_secure: true   
        cookie_same_site: "lax"  
        key: '%env(TRUSTED_DEVICE_SECRET)%'
```

And this is my security.yml:

```yaml
security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        #in_memory: { memory: null }
        my_provider:
            entity: { class: App\Entity\User, property: email }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            #lazy: true
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                provider: my_provider
                #multi_factor: true
                enable_csrf: true
            custom_authenticators:
                - App\Security\DrupalAuthenticator
            login_throttling:
                max_attempts: 3
            logout: true
    role_hierarchy:
        ROLE_MANAGER: [ROLE_USER]
        ROLE_ADMIN: [ROLE_USER, ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, roles: PUBLIC_ACCESS }
        - { path: ^/2fa$, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }

```

It's also registering the routes correctly:

```
  2fa_login                       ANY           ANY      ANY    /2fa                                                 
  2fa_login_check                 ANY           ANY      ANY    /2fa_check 
```

Entity\User.php implements `TwoFactorInterface`.

Do you have any thoughts? I'm just at a loss why it was working before I upgraded 2fa but now it just skips it altogether.

Love the bundle otherwise, thank you! :)

**Additional Context**

This is an older app that I took over and I'm trying to upgrade. It works fine on a new Symfony app I just made with a UsernamePasswordForm token too but not in this app. 

Thanks for any help <3
