### ISSUE TITLE
User is not in a two-factor authentication process.

### ISSUE THREAD

**Issue by vadimoncheck** [scheb/2fa#285]
Here is my configuration

```php
class User implements UserInterface, PasswordAuthenticatedUserInterface, TwoFactorInterface
{
  #[ORM\Column(type: "string", nullable: true)]
      private ?string $googleAuthenticatorSecret = null;


    public function getGoogleAuthenticatorSecret(): ?string
    {
        return $this->googleAuthenticatorSecret;
    }

    public function setGoogleAuthenticatorSecret(?string $googleAuthenticatorSecret): void
    {
        $this->googleAuthenticatorSecret = $googleAuthenticatorSecret;
    }

    public function isGoogleAuthenticatorEnabled(): bool
    {
        return null !== $this->googleAuthenticatorSecret;
    }

    public function getGoogleAuthenticatorUsername(): string
    {
        return $this->email;
    }
}
```

security.yaml

```yaml
security:
          admin:
            provider: app_user_email_provider
            pattern: ^/admin
            form-login:
                login_path: app.easy_admin.login
                check_path: app.easy_admin.login
#                enable_csrf: true
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: /admin

            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 2592000
                path: /admin
                always_remember_me: true

            logout:
                path: admin/logout
                target: app.easy_admin.login
```

scheb_2fa.yaml

```yaml
  scheb_two_factor:
      google:
          enabled: true
          server_name: ProfiCRM
          issuer: CRM
          digits: 6
          window: 1
```

I attached a screenshot of where the error occurs.

![Image](https://github.com/user-attachments/assets/d37475fe-3cb4-4ef0-a05f-5127f7bb9000)
