### ISSUE TITLE
Cannot get simple code-via-email form showing anywhere

### ISSUE THREAD

**Issue by back-2-95** [scheb/2fa#286]
**Bundle version**: 7.10.1
**Symfony version**: 7.3.0
**PHP version**: 8.4.8

**Description**

I'm trying to implement the simple code via email: https://symfony.com/bundles/SchebTwoFactorBundle/current/providers/email.html

I don't get /2fa route showing me anything or I don't know how I could render the form on my own controller/template. I have browsed all your documentation.

**Additional Context**

- routes are there (default values)
- User entity uses TwoFactorInterface and has the methods

scheb_2fa.yaml:

```yaml
# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/6.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    email:
        enabled: true
        sender_email: my@email.com
        sender_name: My App
        digits: 6
```

security.yaml:

```yaml
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
            logout:
                path: /logout

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # This makes the logout route accessible during two-factor authentication. Allows the user to
        # cancel two-factor authentication, if they need to.
        - { path: ^/logout, role: PUBLIC_ACCESS }
        # This ensures that the form can only be accessed when two-factor authentication is in progress.
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
```

If I go to `/2fa` - I get just redirected to `/?` - nothing on logs.
