### ISSUE TITLE
How to change default path 2fa

### ISSUE THREAD

**Issue by VIETDEPTRAII** [scheb/2fa#36]
**Bundle version**: x.y.z
**Symfony version**: x.y.z

**Description**

- Hello, Currently I have a path that is **localhost/admin/_2fa_**. But I want to change **2fa to another-name** -> **localhost/admin/_another-name_**. How can I do it, I tried to change it in routes.yaml, but it didn't work. Could you please help me? Thank you

**Additional Context**

- My routes.yaml file
```yaml
2fa_login:
    path: '/%eccube_admin_route%/2fa'
    defaults:
        # "scheb_two_factor.form_controller" references the controller service provided by the bundle.
        # You don't HAVE to use it, but - except you have very special requirements - it is recommended.
        _controller: Customize\Controller\Admin\AdminController::get2FA

2fa_login_check:
    path: '/%eccube_admin_route%/2fa_check'
```
