### ISSUE TITLE
Cannot Implementing a custom two-factor authenticator

### ISSUE THREAD

**Issue by VIETDEPTRAII** [scheb/2fa#37]
**Bundle version**: x.y.z
**Symfony version**: x.y.z

**Description**

- Hi. Currently, I cannot implement a custom two-factor authenticator. I tried to configure my own two-factor authenticator follow your redirection, but it didn't work. I think, maybe it's wrong in my service file. Could you please help me? Thank you 

**Additional Context**

1. I created a service, then implement Scheb\TwoFactorBundle\Security\TwoFactor\Provider\TwoFactorProviderInterface and add requires methods to follow your direction
2. I register it in my service file:
```yaml
    role.custom_two_factor_authenticator_service:
        alias: Plugin\Role\Service\CustomTwoFactorAuthenticatorService
        tags: ['scheb_two_factor.provider']
```
**-> Maybe, I'm wrong when registering it in the service file or miss some steps. Could you help me out, please? Thank you**

**Comment by scheb** [comment]
The service configuration should look like this:

```yaml
    role.custom_two_factor_authenticator_service:
        class: Plugin\Role\Service\CustomTwoFactorAuthenticatorService
        tags:
            - { name: scheb_two_factor.provider, alias: "my_custom_two_factor_provider" }
```
