### ISSUE TITLE
New Authenticator Manager with "Two-Factor Authentication in an API" approach does not prepare TOTP provider

### ISSUE THREAD

**Issue by eXtreme** [scheb/2fa#42]
**Bundle version**: 5.2.1
**Symfony version**: 5.2.1
**PHP version**: 7.4
**Using authenticators** (`enable_authenticator_manager: true`): **YES**

**Description**
So I use this approach from docs: https://github.com/scheb/2fa/blob/5.x/doc/api.md to implement 2FA in JSON api for Single-Page App.  Handlers are basically the same as in docs.

```
    enable_authenticator_manager: true
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: .*
            lazy: true
            provider: app_users
            logout:
                path: api_logout
                invalidate_session: true
            two_factor:
                auth_form_path: api_2fa_login
                check_path: api_2fa_check
                prepare_on_login: true
                prepare_on_access_denied: true
                authentication_required_handler: App\Security\TwoFactorRequiredHandler
                success_handler: App\Security\TwoFactorSuccessHandler
                failure_handler: App\Security\TwoFactorFailureHandler
            json_login:
                check_path: api_login
                success_handler: App\Security\LoginSuccessHandler
    access_control:
        - { path: '^/logout', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/2fa', roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

`Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken` is also enabled in config.

Sending a code to check_path results in AuthenticationException with the following message:

>  The two-factor provider "totp" has not been prepared.

I've seen a recent bugreport (https://github.com/scheb/2fa/issues/39) with lazy firewalls but changing `lazy: true` to `false` does not fix it (I'm also on newest version). So I guess it has something to do with `prepare_on_login`. 

I reproduced it also on a simple website-skeleton so it's not something weird in my real app.

Removing `enable_authenticator_manager` fixes the issue.
