### ISSUE TITLE
Custom TwoFactorProvider not calling prepareAuthentication

### ISSUE THREAD

**Issue by frost-byte** [scheb/2fa#47]
**Bundle version**: 5.2.1
**Symfony version**: 5.2.1
**PHP version**: 7.2.24

**Description**
***Background***
I am attempting to create a custom provider, one that uses Twilio Verify email 2fa.
The Verify API generates it's own verification code as a part of the service, one that I cannot see directly.
I can authenticate the code submitted via a form by sending a verification check to the Twilio Verify API.

I'm using Webpack Encore with a Vue.js front end; `security.yaml` configuration has a `json_login` and an entry for `two_factor`.

So far I'm able to use my login form and authenticate the user, the front end appears to behave properly, as it brings up my 2fa
form. (although, that's mostly due to how my vue/vuex/axios configuration is interpreting the response from Symfony).

I'm not certain, but it may be something to do with Roles, should it not switch to `IS_AUTHENTICATED_2FA_IN_PROGRESS`?
The log output below shows that the credentials are unset, is that okay?
Another detail I just noticed is that the provider I created is listed in `twoFactorProviders`, but it is not listed under `preparedProviders`

```
[credentials:Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken:private] => 
[providerKey:Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken:private] => main
[attributes:Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken:private] => Array ( )
[twoFactorProviders:Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken:private] => Array ( [0] => twilio_two_factor )
[preparedProviders:Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken:private] => Array ( ) )
```

**Additional Context**

I added some log output to show details for the Token when TwoFactorProviderPreparationListener::onLogin is fired.  It indicates that it is a `Scheb\TwoFactorBundle\Security\Authentication\Token\TwoFactorToken` and it appears to be the correct provider.

I created a class that implements Symfony\Component\Security\Guard\AbstractGuardAuthenticator, which provides the Guard authenticator (which provides the security token)

***Profiler Screenshots***

****Events****
![image](https://user-images.githubusercontent.com/852776/104829869-557ad380-5846-11eb-9ef7-d792db789497.png)

****Log****
![image](https://user-images.githubusercontent.com/852776/104829830-b5bd4580-5845-11eb-9093-5b56b370672b.png)

****Security Token****
![image](https://user-images.githubusercontent.com/852776/104829843-f4eb9680-5845-11eb-92ef-d62147702fec.png)

***config***
```yaml
# config/packages/scheb_2fa.yaml
scheb_two_factor:
    email:
        enabled: false
    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
```

```yaml
# config/packages/security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        users_in_memory: { memory: null }
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\EmailAuthenticator
            logout:
                path: app_logout
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                default_target_path: /dashboard
                always_use_default_target_path: false
                prepare_on_login: true
                prepare_on_access_denied: true
                authentication_required_handler: App\Security\TwoFactor\Handler\TwoFactorRequiredHandler
                success_handler: App\Security\TwoFactor\Handler\TwoFactorSuccessHandler
                failure_handler: App\Security\TwoFactor\Handler\TwoFactorFailureHandler
            json_login:
                check_path: app_login
                success_handler: App\Security\TwoFactor\Handler\LoginSuccessHandler

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN,ROLE_SUPER_ADMIN]
        ROLE_ADMIN: [ROLE_USER,ROLE_ADMIN]
        ROLE_USER: [ROLE_USER]

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/security/2fa_check, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/admin, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/profile, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```
