### ISSUE TITLE
2FA Bundle with JWT Bundler 

### ISSUE THREAD

**Issue by MyZik** [scheb/2fa#50]
**Bundle version**: 5.3.1
**Symfony version**: 4.4
**PHP version**: 7.4
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**
Hi, thank you for your great work! I want to use 2FA via **Email**. Now I have 3 steps in my API:

1. User register with email and password.
2. Login user and get the JWT token.
3. Use the API with the given Bearer Token.

But, I would like to add 2 more steps:

1. User register with email and password.
2. Login user with email and password.
3. **If success: send an E-Mail with 2FA code to user**
4. **Login User but with third parameter for 2FA from Email. email, password, 2fa_token**
5. **If success - response with a bearer token.**
6. Use the API with the given Bearer Token.

My security.yml

```yaml
security:
  providers:
    app_user_provider:
      id: app.security.user_provider

  firewalls:
    login:
      pattern: ^/api/v1/login
      stateless: true
      anonymous: true
      provider: app_user_provider
      json_login:
        check_path: /api/v1/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    register:
      pattern: ^/api/v1/register
      stateless: true
      anonymous: true
      provider: app_user_provider

    api:
      pattern: ^/api/v1
      stateless: true
      provider: app_user_provider
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator
      two_factor:
        prepare_on_login: true
        prepare_on_access_denied: true
        check_path: 2fa_login_check

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true

  access_control:
    - { path: ^/api/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1,       roles: IS_AUTHENTICATED_FULLY }

```

**Additional Context**
I tried to use an example from here: https://github.com/scheb/2fa/blob/5.x/doc/api.md

But it doesn't work:
<img width="629" alt="Bildschirmfoto 2021-01-22 um 13 15 36" src="https://user-images.githubusercontent.com/12817320/105489686-ee30a980-5cb3-11eb-817f-8b27e86c9aaa.png">

The event doesn't provide to get the token interface.

How can I do this? Thank you a lot in advance.
