### ISSUE TITLE
Argument #3 ($token) must be of type TokenInterface, null given

### ISSUE THREAD

**Issue by PhilETaylor** [scheb/2fa#52]
**scheb/2fa**: v5.4.1
**symfony**: v5.2.2
**PHP version**: 8.0.3-dev (unrelated, had issues before 8)
**Using authenticators** (`enable_authenticator_manager: true`): YES 

**Description**

I use Sentry.io to capture unhandled exceptions.

VERY rarely I get this same exception. Previously I just ignored it, today I had time to report to you for your thoughts. 

The request is a POST to the /2fa_check route with a param of `_auth_code` and a 6digit user supplied code when the exception is thrown. 

```
TypeError: Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator::dispatchTwoFactorAuthenticationEvent(): Argument #3 ($token) must be of type Symfony\Component\Security\Core\Authentication\Token\TokenInterface, null given, called in /var/www/current/vendor/scheb/2fa/src/bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php on line 169
#17 /var/www/current/vendor/scheb/2fa/src/bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php(174): Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator::dispatchTwoFactorAuthenticationEvent
#16 /var/www/current/vendor/scheb/2fa/src/bundle/Security/Http/Authenticator/TwoFactorAuthenticator.php(169): Scheb\TwoFactorBundle\Security\Http\Authenticator\TwoFactorAuthenticator::onAuthenticationFailure
#15 /var/www/current/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(235): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::handleAuthenticationFailure
#14 /var/www/current/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(190): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticator
#13 /var/www/current/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(145): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::executeAuthenticators
#12 /var/www/current/vendor/symfony/security-http/Authentication/AuthenticatorManager.php(125): Symfony\Component\Security\Http\Authentication\AuthenticatorManager::authenticateRequest
#11 /var/www/current/vendor/symfony/security-http/Firewall/AuthenticatorManagerListener.php(42): Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener::authenticate
#10 /var/www/current/vendor/symfony/security-http/Firewall/AbstractListener.php(26): Symfony\Component\Security\Http\Firewall\AbstractListener::__invoke
#9 /var/www/current/vendor/symfony/security-bundle/Security/LazyFirewallContext.php(60): Symfony\Bundle\SecurityBundle\Security\LazyFirewallContext::__invoke
#8 /var/www/current/vendor/symfony/security-http/Firewall.php(113): Symfony\Component\Security\Http\Firewall::callListeners
#7 /var/www/current/vendor/symfony/security-http/Firewall.php(86): Symfony\Component\Security\Http\Firewall::onKernelRequest
#6 /var/www/current/vendor/symfony/event-dispatcher/EventDispatcher.php(270): Symfony\Component\EventDispatcher\EventDispatcher::Symfony\Component\EventDispatcher\{closure}
#5 /var/www/current/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\EventDispatcher::callListeners
#4 /var/www/current/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher::dispatch
#3 /var/www/current/vendor/symfony/http-kernel/HttpKernel.php(133): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#2 /var/www/current/vendor/symfony/http-kernel/HttpKernel.php(79): Symfony\Component\HttpKernel\HttpKernel::handle
#1 /var/www/current/vendor/symfony/http-kernel/Kernel.php(195): Symfony\Component\HttpKernel\Kernel::handle
#0 /var/www/current/public/index.php(31): null
```

**To Reproduce**

Sorry I cannot tell you how its produced. 

**Additional Context**
https://sentry.io/share/issue/66fe1c30a92046f6b7f833e31f3695ac/

**Comment by scheb** [comment]
Looks as if there's a request against `/2fa_check` when the user hasn't even completed the initial login yet.

Would you please post your `security.yaml` configuration?

**Comment by PhilETaylor** [comment]
Correct, I just did a POST using command line to /2fa_check and replicated the error in dev. 

I can't post the whole yaml but here are relevant parts... 

```
main:
      pattern: /
      host: "%manage_subdomain%.mysites.guru"
      remember_me:
        secret:   '%kernel.secret%'
        lifetime: 2592000 # 1 month in seconds
        path:     /
        httponly: true
        samesite: 'strict'
        name: _rememberme
      two_factor:
        auth_form_path: 2fa_login
        check_path: 2fa_login_check
      custom_authenticators:
        - Base\Security\Authenticator
      lazy: true
      provider: users
      switch_user:  { parameter: _switch_user }
      logout:
        path: app_logout

- { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
```
