### ISSUE TITLE
Enable 2 factor module configuration via environment variables

### ISSUE THREAD

**Issue by aturki** [scheb/2fa#54]
Right now configuring modules via environment variables is not supported for instance, the following configuration is does not work:

```yaml
scheb_two_factor:
  email:
    enabled: '%env(ENABLE_2FA)%'
```

**Comment by Spomky** [comment]
What about the `bool` env processor ?
https://symfony.com/doc/current/configuration/env_var_processors.html#built-in-environment-variable-processors

```yaml
scheb_two_factor:
  email:
    enabled: '%env(bool:ENABLE_2FA)%'
```
