### ISSUE TITLE
Set different templates per firewall

### ISSUE THREAD

**Issue by virtualize** [scheb/2fa#58]
We use two different firewalls (backend, frontend) and need to set the 2fa template (google & totp) used per firewall.
As far as I can see this is not possible via configuration. Is there a way I'm not aware of or do I need to set up different TwoFactorFormRenderers? 

**Bundle version**: 5.4
**Symfony version**: 4.4
**PHP version**: 7.4
**Using authenticators** (`enable_authenticator_manager: true`): YES / NO

**Description**
````
# security.yaml
security:
    firewalls:
        # backend firewall
        admin:
            pattern: ^/admin
            guard:
                provider: admin_user_provider
                authenticators: [App\Security\AdminFormAuthenticator]
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                name: remember_me
                path: /admin
            two-factor:
                provider: admin_user_provider
                auth_form_path: admin_2fa_login
                check_path: admin_2fa_login_check
            logout:
                path: admin_logout
                target: admin_login
            anonymous: true

        main:
            pattern: ^/
            guard:
                provider: frontend_user_provider
                authenticators: [App\Security\FrontendFormAuthenticator]
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000 # 30 days in seconds
                name: remember_me
                path: /
            two-factor:
                provider: frontend_user_provider
                auth_form_path: frontend_2fa_login
                check_path: frontend_2fa_login_check
            logout:
                path: frontend_logout
                target: frontend_login
            anonymous: true
````

Thanks for any pointers.

**Comment by scheb** [comment]
That's unfortunately not really supported.

You could either distiguish the firewalls in the template code, put an if condition there to render either the one or the other view. Or you could overwrite the renderer service with a custom one.

This last one is a bit "hacky", since you'd overwrite internal services from the bundle. I'm thinking this should probably be a configuration setting 🤔, so you can inject a custom renderer service the proper way. Otherwise it has a bit of a risk to break with a future update if renderer service names change - unlikely, but may happen.

**Comment by virtualize** [comment]
Thanks Christian for your fast reply. 
I took the easy way with a template condition, could have figured that out myself 😄 

```twig
{% if app.request.attributes.get('_firewall_context') ends with 'admin' %}
    {% include 'admin/security/2fa_google.html.twig' %}
{% else %}
    {% include 'frontend/security/2fa_google.html.twig' %}
{% endif %}
````

**Comment by scheb** [comment]
Looks a bit ugly, but yea, should do the job ;)

I've created an issue to add a configuration option for a custom form renderer, will add that at some point.

**Comment by scheb** [comment]
With version 5.7.0 there's a configuration now to set a custom form renderer service for each 2fa provider (email, totp, google authenticator).

See: https://github.com/scheb/2fa/blob/5.x/doc/configuration.md

**Comment by virtualize** [comment]
For anyone searching for a reusable solution:

**config/packages/scheb_two_factor.yaml**
```yaml
scheb_two_factor:
    google:
        enabled: true
        form_renderer: 'scheb_two_factor.google.form_renderer'

services:
    scheb_two_factor.google.form_renderer:
        class: App\Security\TwoFactorFirewallTemplatesFormRenderer
        arguments:
            - '@twig'
            - '@security.firewall.map'
            - { main: 'security/2fa_google.html.twig', admin: 'admin/security/2fa_google.html.twig' } ]
```

**src/Security/TwoFactorFirewallTemplatesFormRenderer.php**
```php
<?php

namespace App\Security;

use Scheb\TwoFactorBundle\Security\TwoFactor\Provider\TwoFactorFormRendererInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Http\FirewallMapInterface;
use Twig\Environment;

class TwoFactorFirewallTemplatesFormRenderer implements TwoFactorFormRendererInterface
{
    private Environment $twigEnvironment;
    private FirewallMapInterface $firewallMap;
    private array $templates; // array of items [firewall name => template path]
    
    public function __construct(
        Environment $twigRenderer,
        FirewallMapInterface $firewallMap,
        array $templates
    ) {
        $this->twigEnvironment = $twigRenderer;
        $this->firewallMap = $firewallMap;
        $this->templates = $templates;
    }
    
    public function renderForm(Request $request, array $templateVars): Response
    {
        $firewallName = $this->firewallMap->getFirewallConfig($request)->getName();
        $template = $this->templates[$firewallName];
        
        $content = $this->twigEnvironment->render($template, $templateVars);
        $response = new Response();
        $response->setContent($content);

        return $response;
    }
}

```
