### ISSUE TITLE
Symfony v5.3.0-BETA1 issue with remember me.

### ISSUE THREAD

**Issue by PhilETaylor** [scheb/2fa#75]
**Bundle version**: dev-master
**Symfony version**: v5.3.0-BETA1
**PHP version**: 8.0.6-dev
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**

After upgrading (as a test) to Symfony v5.3.0-BETA1 on a normally working large application, the first issue I come against is this:

<img width="1076" alt="Screenshot 2021-04-21 at 19 57 48" src="https://user-images.githubusercontent.com/400092/115607026-58b9ab80-a2dc-11eb-89d4-7a08bd61d525.png">

**To Reproduce**

Have a working site, with Scheb/2fa 5.x and upgrade to Symfony v5.3.0-BETA1

**Additional Context**

Im happy to debug for you - let me know what you might need.

**Comment by PhilETaylor** [comment]
hmm might be related to this https://github.com/symfony/symfony/pull/40145 ?  I have commented out my remember_me configs and I can now load a page

```
# EXAMPLE ONLY - out of context of my app. 

firewalls:
    main:
      pattern: /
      host: "%manage_subdomain%.mysites.guru"
#      remember_me:
#        secret:   '%kernel.secret%'
#        lifetime: 2592000 # 1 month in seconds
#        path:     /
#        httponly: true
#        samesite: 'strict'
#        name: _rememberme
```
