### ISSUE TITLE
After successful log in, 2FA takes me to the /favicon.ico path instead of the normal log in path

### ISSUE THREAD

**Issue by pixelcommerce** [scheb/2fa#76]
Everything works perfectly fine other than the fact that after the user authenticates fully (pw -> google 2FA) the user is forwarded to the `/favicon.ico` path instead of the normal path that the user can follow.

Why is this happening?

**Comment by scheb** [comment]
That's weird.

Is the `/favicon.ico` path delivered by the Symfony application? What happens when you call that path?

My assumption is that path is hitting the Symfony application and is somehow "secured". So when Symfony wants you to log in, that's the last path it has seen from you last, and therefore that's where it redirects you after log in.

**Comment by pixelcommerce** [comment]
Hey @scheb thanks for the fast response.

Unfortunately not, I do not have that path on my application. Usually what my application does is it takes you one of two places:

1) The homepage (which is pathed to /) if you haven't gone to a page that requires auth.
2) Redirects to a page previous to login (so if I went to say /account before log in, it will redirect there)

Currently, regardless of what I do, it will redirect to /favicon.ico which is weird.

**Comment by scheb** [comment]
Well, it doesn't need to be explicitly configured in your application. Maybe you have some "catch all" functionality in your application that makes all paths hit the Symfony application.

In any case, for some reason the last path that Symfony sees from you, seems to be `/favicon.ico` path. If you don't want to investigate that in-depth, a workaround could be to configure a specific `default_target_path` and force that path via `always_use_default_target_path`:

```yaml
# config/packages/security.yaml
security:
    firewalls:
        your_firewall_name:
            # ...
            two_factor:
                default_target_path: /                # Where to redirect by default after successful authentication
                always_use_default_target_path: true # If it should always redirect to default_target_path
```
