### ISSUE TITLE
Stateless API authentication. How to prepare two factor providers?

### ISSUE THREAD

**Issue by koekaverna** [scheb/2fa#78]
**Bundle version**: 5.8.0
**Symfony version**: 5.2.6
**PHP version**: 7.4.16
**Using authenticators** (`enable_authenticator_manager: true`): YES

**Description**
Hello and thank you for work on this great project!

I'm using this package for stateless api. And i finaly made working solution. After authentication I create and store token to redis database and cookie. And before two-factor code check I authenticate User from this token.   
But I don't have idea how properly prepare two factor providers.

This is my security.yaml
```yaml
security:
    enable_authenticator_manager: true
    providers:
        user_provider:
            entity:
                class: App\Entity\User
        jwt:
            lexik_jwt: ~

    firewalls:
        auth:
            pattern: ^/auth/
            provider: user_provider
            stateless: true
            entry_point: App\Security\Http\Authenticator\AuthenticationEntryPoint
            custom_authenticators:
                - App\Security\Http\Authenticator\TwoFactorTokenAuthenticator
            json_login:
                check_path: auth_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            two_factor:
                check_path: auth_2fa_check
                auth_code_parameter_name: authCode
                prepare_on_login: true
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: auth_logout

        main:
            pattern:  ^/
            provider: jwt
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```

**Additional Context**

```php
final class TwoFactorTokenAuthenticator implements AuthenticatorInterface
{
    private TokenManagerInterface $twoFactorTokenManager;

    private TokenExtractorInterface $twoFactorTokenExtractor;

    public function __construct(TokenManagerInterface $twoFactorTokenManager, TokenExtractorInterface $twoFactorTokenExtractor)
    {
        $this->twoFactorTokenManager = $twoFactorTokenManager;
        $this->twoFactorTokenExtractor = $twoFactorTokenExtractor;
    }

    public function supports(Request $request): ?bool
    {
        return $this->twoFactorTokenExtractor->extract($request) !== false;
    }

    public function authenticate(Request $request): PassportInterface
    {
        $tokenString = $this->twoFactorTokenExtractor->extract($request);
        if ($tokenString === false) {
            throw new \LogicException('Can not extract token from request.');
        }
        $usernameToken = $this->twoFactorTokenManager->get($tokenString);
        if ($usernameToken === null) {
            throw new TokenNotFoundException('Two-factor token not found.');
        }
        $request->attributes->set('_two_factor_token', $tokenString);

        return new SelfValidatingPassport(new UserBadge($usernameToken->getUsername()));
    }

    public function createAuthenticatedToken(PassportInterface $passport, string $firewallName): TokenInterface
    {
        if (!$passport instanceof Passport) {
            throw new \LogicException(sprintf('Passport should be instance of "%s".', Passport::class));
        }

        $token = new TwoFactorToken(
            new PostAuthenticationToken($passport->getUser(), $firewallName, $passport->getUser()->getRoles()),
            null,
            $firewallName,
            ['google']
        );
        $token->setTwoFactorProviderPrepared('google');

        return $token;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, string $providerKey): ?Response
    {
        return null;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception): ?Response
    {
        return null;
    }
}
```

and this is SuccessHandlerDecorator:
```php
    public function onAuthenticationSuccess(Request $request, TokenInterface $token)
    {
        if ($token instanceof TwoFactorTokenInterface) {
            $identity = $token->getUser();
            if ($identity instanceof GoogleTwoFactorAssociatedIdentityInterface) {
                $usernameToken = UsernameToken::createFromUsername($identity->getUsername());
                $this->twoFactorTokenManager->save($usernameToken);
                $cookie = $this->twoFactorTokenCookieProvider->createCookie($usernameToken->getToken());
                $response = new JsonResponse(['status' => 'AUTHENTICATION_REQUIRED']);
                $response->headers->setCookie($cookie);

                return $response;
            }
        }

        $response = $this->decoratedSuccessHandler->onAuthenticationSuccess($request, $token);

        // Clear two-factor token and cookie after successfully authentication
        if ($request->attributes->has('_two_factor_token')) {
            $this->twoFactorTokenManager->delete($request->attributes->get('_two_factor_token'));
            $response->headers->setCookie($this->twoFactorTokenCookieProvider->clearCookie());
        }

        return $response;
    }
```

Hope this idea can help other peoples who interested in using this package with stateless API.
