### ISSUE TITLE
Two issues: Remember doesnt work, and how do I check if QR code was scanned?

### ISSUE THREAD

**Issue by pixelcommerce** [scheb/2fa#83]
For the latest version, I was wondering if there was a way where you could check if the user had scanned the QR code for the google authenticator? Because right now, we only display the QR code once, and if you missed it, that sucks for you (horrible UX). Is there a way where we can check if the user scanned the QR code?

Also I noticed after installing the google authenticator, the remember me function isn't working. Maybe there is something I'm missing?

Thanks for the help, and sorry for what seems to be obvious questions.

**Comment by scheb** [comment]
> For the latest version, I was wondering if there was a way where you could check if the user had scanned the QR code for the google authenticator? Because right now, we only display the QR code once, and if you missed it, that sucks for you (horrible UX). Is there a way where we can check if the user scanned the QR code?

Let the user confirm that they have scanned the QR code, only then activate 2fa.

> Also I noticed after installing the google authenticator, the remember me function isn't working. Maybe there is something I'm missing?

Please explain "remember me function isn't working". And please provide the information that the issue template is asking you for, otherwise I can't help you.

**Comment by pixelcommerce** [comment]
For the first option, makes sense. I'll make the update on our end.

As for the second issue, I've been noticing that when I check the "remember me function," because 2FA is enabled (the google one), remember is no longer functioning. This is my security.yaml firewall parameters:

```
firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            login_throttling:
                limiter: app.custom.limiter
            lazy: true
            provider: app_user_provider
            two_factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
                # where to redirect after logout
                # target: app_any_route
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
```
