### ISSUE TITLE
Allow environment variable use in configuration

### ISSUE THREAD

**Issue by gnat42** [scheb/2fa#86]
## Problem Desc
We have 2fa enabled on our production instance. We use the IP whitelist so that local development disables 2FA. Recently we've started using a centralized QA server. This server doesn't send email or any outbound messages. It uses the symfony prod environment. So I'd like to disable the email via an environment parameter. I created one that is in our .env file PROJECT_ENABLE_2FA=false and edited 

``` 
//config/packages/scheb_two_factor.yaml
scheb_two_factor:
    email:
        enabled: '%env(PROJECT_ENABLE_2FA)%'
```
However when I do this email auth is still attempting to send a 2fa and I'm presented with a request for the code. Using xdebug I could see that the code in [SchebTwoFactorExtenstion.php](https://github.com/scheb/2fa/blob/5.x/src/bundle/DependencyInjection/SchebTwoFactorExtension.php#L39) should be disabling it, however the code
```
$this->resolveFeatureFlag($container, $config['email']['enabled'])
```

returns the string "false" so it's not actually false because if("string") isn't a falsey value. I looked at some docs and then tried

``` 
//config/packages/scheb_two_factor.yaml
scheb_two_factor:
    email:
        enabled: '%env(bool:PROJECT_ENABLE_2FA)%'
```

However now I get an error

```
Using a cast in "env(bool:PROJECT_ENABLE_2FA)" is incompatible with resolution at compile time in "Scheb\TwoFactorBundle\DependencyInjection\SchebTwoFactorExtension". The logic in the extension should be moved to a compiler pass, or an env parameter with no cast should be used instead.
````

I don't know the right way to solve this. I could submit a pull request so that this->resolveFeatureFlag if not a boolean then looks for the string "true"|"false"|"on"|"off" and returns an appropriate boolean otherwise it returns the value. I think that should be backwards compatible in the library. I just don't know if the symfony error its throwing points to a better way to solve it. I'm not a huge fan of the environment variable addition to symfony as I keep running into weird issues like this that didn't occur with parameters.yml files. I know that's not your fault, I'm just point it out as I don't know the correct solution. If you're happy enough with a PR to fix this here I will happy draft one up for you quickly.
