### ISSUE TITLE
How to implement resend code functionality

### ISSUE THREAD

**Issue by oleshek** [scheb/2fa#97]
**Bundle version**: scheb/2fa-bundle: 5.10.1, scheb/2fa-email: 5.10.1
**Symfony version**: 5.2.10
**PHP version**: 8.0.3

**Description**

I have implemented two-factor authentication based on email code in my app. After user enter his email and password, system redirects him to /2fa route where he need to enter code from email. Everything works great. But I don't understand how to implement resend code functionality. The small advice [in doc](https://github.com/scheb/2fa/blob/5.x/doc/providers/email.md#re-send-authentication-code) isn't enough for me. Please help.

**Additional Context**

config/packages/security.yaml
```yaml
security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route
                
            access_denied_handler: App\Security\AccessDeniedHandler

            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
            
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: '^/2fa', roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/logout', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/register', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/reset-password', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/verify/email', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```

config/packages/scheb_2fa.yaml
```yaml
scheb_two_factor:
    security_tokens:
         - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken
    email:
        enabled: true
        mailer: 2fa_mailer
        template: security/2fa_form.html.twig
        digits: 6
</div></pre></code>

config/routes.yaml
<div class="snippet-clipboard-content position-relative"><pre><code>
2fa_login:
    path: /2fa
    defaults:
        # "scheb_two_factor.form_controller" references the controller service provided by the bundle.
        # You don't HAVE to use it, but - except you have very special requirements - it is recommended.
        _controller: "scheb_two_factor.form_controller:form"

2fa_login_check:
    path: /2fa_check
```
